trainingInput:
  scaleTier: BASIC_GPU
  hyperparameters:
    goal: MAXIMIZE
    hyperparameterMetricTag: accuracy
    maxTrials: 35
    maxParallelTrials: 7
    params:
      - parameterName: hp-conv1
        type: INTEGER
        minValue: 6
        maxValue: 11
        scaleType: UNIT_LINEAR_SCALE
      - parameterName: hp-conv2
        type: INTEGER
        minValue: 12
        maxValue: 23
        scaleType: UNIT_LINEAR_SCALE
      - parameterName: hp-conv3
        type: INTEGER
        minValue: 24
        maxValue: 48
        scaleType: UNIT_LINEAR_SCALE
#
# Other params:
# three conv layers: with patch sizes 6x6 5x5 4x4
# dense layer: 200
# activation: relu
#
# comment: awaiting results...